# Generated by Django 5.0.4 on 2024-05-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('second_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_card_copy', models.FileField(upload_to='aadhar/')),
                ('pan_card_copy', models.FileField(upload_to='pan/')),
                ('college_mark_sheet', models.FileField(upload_to='college_marks/')),
                ('twelfth_mark_sheet', models.FileField(upload_to='12th_marks/')),
                ('tenth_mark_sheet', models.FileField(upload_to='10th_marks/')),
                ('is_trainee', models.BooleanField(default=False)),
                ('is_team_member', models.BooleanField(default=False)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_admin_assistant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('employees', models.ManyToManyField(related_name='roles', to='frontend.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='frontend.employeedetail')),
                ('members', models.ManyToManyField(related_name='teams', to='frontend.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.employeedetail')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.team')),
            ],
        ),
    ]
