# Generated by Django 5.0.4 on 2024-06-04 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('second_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_card_copy', models.FileField(blank=True, null=True, upload_to='aadhar/')),
                ('pan_card_copy', models.FileField(blank=True, null=True, upload_to='pan/')),
                ('college_mark_sheet', models.FileField(blank=True, null=True, upload_to='college_marks/')),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('twelfth_mark_sheet', models.FileField(blank=True, null=True, upload_to='12th_marks/')),
                ('tenth_mark_sheet', models.FileField(blank=True, null=True, upload_to='10th_marks/')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('is_trainee', models.BooleanField(default=False)),
                ('is_team_member', models.BooleanField(default=False)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_admin_assistant', models.BooleanField(default=False)),
                ('creative', models.BooleanField(default=False)),
                ('digital_marketin', models.BooleanField(default=False)),
                ('development', models.BooleanField(default=False)),
                ('client_relationship', models.BooleanField(default=False)),
                ('Graphic_designer', models.BooleanField(default=False)),
                ('Video_Editing', models.BooleanField(default=False)),
                ('Social_Media_Management', models.BooleanField(default=False)),
                ('Content_Creation', models.BooleanField(default=False)),
                ('Search_Engine_Optimization', models.BooleanField(default=False)),
                ('Contant_Writing', models.BooleanField(default=False)),
                ('Webside_Development', models.BooleanField(default=False)),
                ('Software_Development', models.BooleanField(default=False)),
                ('App_Development', models.BooleanField(default=False)),
                ('Testing', models.BooleanField(default=False)),
                ('Account_Manager', models.BooleanField(default=False)),
                ('Admin', models.BooleanField(default=False)),
                ('creaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='frontend.employeedetail')),
                ('members', models.ManyToManyField(related_name='teams', to='frontend.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.employeedetail')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.team')),
            ],
        ),
    ]
