# Generated by Django 5.0.4 on 2024-06-24 10:16

import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('second_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_card_copy', models.FileField(blank=True, null=True, upload_to='aadhar/')),
                ('pan_card_copy', models.FileField(blank=True, null=True, upload_to='pan/')),
                ('college_mark_sheet', models.FileField(blank=True, null=True, upload_to='college_marks/')),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('twelfth_mark_sheet', models.FileField(blank=True, null=True, upload_to='12th_marks/')),
                ('tenth_mark_sheet', models.FileField(blank=True, null=True, upload_to='10th_marks/')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('is_trainee', models.BooleanField(default=False)),
                ('is_team_member', models.BooleanField(default=False)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_admin_assistant', models.BooleanField(default=False)),
                ('creative', models.BooleanField(default=False)),
                ('digital_marketin', models.BooleanField(default=False)),
                ('development', models.BooleanField(default=False)),
                ('client_relationship', models.BooleanField(default=False)),
                ('Graphic_designer', models.BooleanField(default=False)),
                ('Video_Editing', models.BooleanField(default=False)),
                ('Social_Media_Management', models.BooleanField(default=False)),
                ('Content_Creation', models.BooleanField(default=False)),
                ('Search_Engine_Optimization', models.BooleanField(default=False)),
                ('Contant_Writing', models.BooleanField(default=False)),
                ('Webside_Development', models.BooleanField(default=False)),
                ('Software_Development', models.BooleanField(default=False)),
                ('App_Development', models.BooleanField(default=False)),
                ('Testing', models.BooleanField(default=False)),
                ('Account_Manager', models.BooleanField(default=False)),
                ('Admin', models.BooleanField(default=False)),
                ('creaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_created_by', to='frontend.employeedetail')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_updated_by', to='frontend.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='customersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('clientname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('companylogo', models.ImageField(blank=True, null=True, upload_to='path/to/upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_customers', to='frontend.employeedetail')),
                ('updatedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_customers', to='frontend.employeedetail')),
                ('products', models.ManyToManyField(related_name='products', to='frontend.producttable')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_img', models.ImageField(blank=True, null=True, upload_to='path/to/upload/')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_of_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Waiting to Start', 'Waiting to Start'), ('Dropped', 'Dropped'), ('Hold', 'Hold'), ('On Process', 'On Process'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Waiting to Start', max_length=16, null=True)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customerstable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(blank=True, choices=[('None', 'None'), ('Gray', 'Gray'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Pink', 'Pink'), ('Purple', 'Purple')], max_length=16, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_project', to='frontend.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='Team Logos/')),
                ('description', models.TextField()),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='frontend.employeedetail')),
                ('members', models.ManyToManyField(related_name='teams', to='frontend.employeedetail')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='frontend.team'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, choices=[('None', 'None'), ('Gray', 'Gray'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Pink', 'Pink'), ('Purple', 'Purple')], max_length=16, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_project', to='frontend.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('ETA', models.IntegerField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=frontend.models.attachment_upload_to)),
                ('assigned_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_from', to='frontend.employeedetail')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_to', to='frontend.employeedetail')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.customerstable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.status')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.type')),
            ],
        ),
    ]
