# Generated by Django 5.0.4 on 2024-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
