# Generated by Django 5.0.4 on 2024-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_events_typeofevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='all_Friday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='all_Monday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='all_Saturday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='all_Sunday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='all_Thursday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='all_Tuesday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='all_Wednesday',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
