# Generated by Django 5.0.4 on 2024-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_employeedetail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
