# Generated by Django 5.0.4 on 2024-06-25 12:33

import django.db.models.deletion
import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='AfterAssignees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_assignees', to='frontend.employeedetail'),
        ),
        migrations.AddField(
            model_name='comments',
            name='AfterAttachment',
            field=models.ImageField(blank=True, null=True, upload_to=frontend.models.comments_image_upload_to),
        ),
        migrations.AddField(
            model_name='comments',
            name='AfterDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='AfterPriority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='AfterStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_status', to='frontend.status'),
        ),
        migrations.AddField(
            model_name='comments',
            name='BeforeAssignees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before_assignees', to='frontend.employeedetail'),
        ),
        migrations.AddField(
            model_name='comments',
            name='BeforeAttachment',
            field=models.ImageField(blank=True, null=True, upload_to=frontend.models.comments_image_upload_to),
        ),
        migrations.AddField(
            model_name='comments',
            name='BeforeDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='BeforePriority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='BeforeStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_status', to='frontend.status'),
        ),
    ]
