# Generated by Django 5.0.4 on 2024-06-05 07:05

import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_employeedetail_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('creaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('creaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CusTomertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=frontend.models.generate_customer_id, max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=20)),
                ('client_number', models.IntegerField()),
                ('org_name', models.CharField(max_length=30)),
                ('org_img', models.ImageField(blank=True, null=True, upload_to=frontend.models.lead_and_customer_companylogo)),
                ('business_type', models.CharField(choices=[('One Time', 'One Time'), ('Recurring', 'Recurring')], max_length=20)),
                ('amount', models.FloatField()),
                ('end_of_date', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('mail_id', models.EmailField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Fresh', 'Fresh'), ('Call Back', 'Call Back'), ('Do Not Disturb', 'Do Not Disturb'), ('Follow up', 'Follow up'), ('Proposed', 'Proposed'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=15)),
                ('comment', models.TextField(max_length=100)),
                ('remarks', models.TextField(max_length=100)),
                ('follow_up', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.citytable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custoner_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.countrytable')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgTypeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(max_length=30)),
                ('creaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=25)),
                ('creaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientDetail',
        ),
        migrations.AddField(
            model_name='customertable',
            name='org_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.orgtypetable'),
        ),
        migrations.AddField(
            model_name='customertable',
            name='products',
            field=models.ManyToManyField(blank=True, to='frontend.producttable'),
        ),
    ]
