# Generated by Django 5.0.4 on 2024-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_events_all_friday_events_all_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='weekday',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
