# Generated by Django 5.0.4 on 2024-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_comments_afterassignees_comments_afterattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='corrent_date_time',
            field=models.DateTimeField(),
        ),
    ]
