# Generated by Django 5.0.4 on 2024-06-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_citytable_countrytable_customertable_orgtypetable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertable',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='org_type',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='customertable',
            name='remarks',
        ),
        migrations.DeleteModel(
            name='CityTable',
        ),
        migrations.DeleteModel(
            name='CountryTable',
        ),
        migrations.DeleteModel(
            name='OrgTypeTable',
        ),
    ]
