# Generated by Django 5.0.4 on 2024-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_comments_corrent_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='working_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='working_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
