# Generated by Django 5.0.4 on 2024-08-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_events_all_team_events_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='all_Sunday',
        ),
        migrations.AlterField(
            model_name='events',
            name='all_Friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='all_Monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='all_Saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='all_Thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='all_Tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='all_Wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='all_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='typeOfEvent',
            field=models.CharField(blank=True, choices=[('Call', 'Call'), ('Event', 'Event'), ('Meeting', 'Meeting')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='weekday',
            field=models.BooleanField(default=True),
        ),
    ]
