# Generated by Django 5.0.4 on 2024-07-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_tasksheet_working_hours_tasksheet_working_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksheet',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='tasksheet',
            name='working_minutes',
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='hold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='tasktimeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('working_hours', models.FloatField(blank=True, default=0, null=True)),
                ('working_days', models.FloatField(blank=True, default=0, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.tasksheet')),
            ],
        ),
    ]
