# Generated by Django 5.0.4 on 2024-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_tasksheet_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='note_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='note_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
