# Generated by Django 5.0.4 on 2024-06-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_projectcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertable',
            name='products',
        ),
        migrations.AddField(
            model_name='customertable',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_table', to='frontend.producttable'),
        ),
    ]
