# Generated by Django 5.0.4 on 2024-06-10 06:16

import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_customertable_products_customertable_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_img', models.ImageField(blank=True, null=True, upload_to=frontend.models.lead_and_customer_companylogo)),
                ('start_date', models.DateField()),
                ('end_of_date', models.DateField()),
                ('status', models.CharField(choices=[('Fresh', 'Fresh'), ('Call Back', 'Call Back'), ('Do Not Disturb', 'Do Not Disturb'), ('Follow up', 'Follow up'), ('Proposed', 'Proposed'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=15)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_categories', to='frontend.team')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custoner_created', to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_table', to='frontend.producttable')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CusTomertable',
        ),
    ]
