# Generated by Django 5.0.4 on 2024-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='color',
            field=models.TextField(),
        ),
    ]
