# Generated by Django 5.0.4 on 2024-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_events_end_time_alter_events_satrt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
