# Generated by Django 5.0.4 on 2024-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_events_meeting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='team',
        ),
        migrations.AddField(
            model_name='events',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.team'),
        ),
    ]
