# Generated by Django 5.0.4 on 2024-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_project_delete_customertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='products',
        ),
        migrations.AddField(
            model_name='project',
            name='project_discription',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
