# Generated by Django 5.0.4 on 2024-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_project_products_project_project_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Call Back', 'Call Back'), ('Do Not Disturb', 'Do Not Disturb'), ('Follow up', 'Follow up'), ('Proposed', 'Proposed'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=15, null=True),
        ),
    ]
