# Generated by Django 5.0.4 on 2024-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_events_team_events_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='team',
            field=models.ManyToManyField(related_name='teams', to='frontend.team'),
        ),
    ]
