# Generated by Django 5.0.4 on 2024-08-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_events_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='all_Friday',
        ),
        migrations.RemoveField(
            model_name='events',
            name='all_Monday',
        ),
        migrations.RemoveField(
            model_name='events',
            name='all_Saturday',
        ),
        migrations.RemoveField(
            model_name='events',
            name='all_Thursday',
        ),
        migrations.RemoveField(
            model_name='events',
            name='all_Tuesday',
        ),
        migrations.RemoveField(
            model_name='events',
            name='all_Wednesday',
        ),
        migrations.RemoveField(
            model_name='events',
            name='weekday',
        ),
    ]
