# Generated by Django 5.0.4 on 2024-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_project_end_of_date_alter_project_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting to Start', 'Waiting to Start'), ('Dropped', 'Dropped'), ('On Process', 'On Process'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=16, null=True),
        ),
    ]
