# Generated by Django 5.0.4 on 2024-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_project_project_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Team Logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting to Start', 'Waiting to Start'), ('Dropped', 'Dropped'), ('On Process', 'On Process'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Closed', 'Closed')], default='Waiting to Start', max_length=16, null=True),
        ),
    ]
