# Generated by Django 5.0.4 on 2024-06-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='description',
        ),
    ]
