# Generated by Django 5.0.4 on 2024-06-15 10:23

import ckeditor.fields
import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_remove_type_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksheet',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='tasksheet',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='tasksheet',
            name='team',
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='ETA',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='assigned_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=frontend.models.attachment_upload_to),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='end_date_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='start_date_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='task_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.status'),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
