# Generated by Django 5.0.4 on 2024-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_remove_tasksheet_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='ETA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
