# Generated by Django 5.0.4 on 2024-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_alter_tasksheet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
