# Generated by Django 5.0.4 on 2024-06-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_alter_tasksheet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='assigned_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_from', to='frontend.employeedetail'),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_to', to='frontend.employeedetail'),
        ),
    ]
