# Generated by Django 5.0.4 on 2024-06-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_rename_project_discription_project_project_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCategories',
        ),
    ]
