# Generated by Django 5.0.4 on 2024-06-20 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_delete_projectcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='creaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_created_by', to='frontend.employeedetail'),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_updated_by', to='frontend.employeedetail'),
        ),
    ]
